### ISSUE TITLE
Change default behavior of Kinesis

### ISSUE THREAD

**Issue by horike37** [horike37/serverless-apigateway-service-proxy#23]
Would like to change default behavior for Kinesis to the following to make more simple.
https://github.com/horike37/serverless-apigateway-service-proxy#customizing-request-body-mapping-templates

Here is the syntax.

```yaml
custom:
  apiGatewayServiceProxies:
    - kinesis:
        path: /kinesis/single
        method: post
        action: PutRecord
        streamName: { Ref: 'YourStream' }
        cors: true

```
