### ISSUE TITLE
add support for DynamoDB

### ISSUE THREAD

**Issue by horike37** [horike37/serverless-apigateway-service-proxy#31]

**Comment by erezrokah** [comment]
Found this project:
https://github.com/ToQoz/api-gateway-mapping-template

Hasn't been updated in a while but still works.

Tested it with the templates and inputs from here:
https://aws.amazon.com/blogs/compute/using-amazon-api-gateway-as-a-proxy-for-dynamodb/

And it still works

**Comment by horike37** [comment]
@erezrokah @theburningmonk 
Great. Thank you for providing us the infomation. the VTL library looks good  😄 
Would love to decide syntax for DynamoDB proxy before working on this so that users can do more flexible configuration.

Probably, it is similar to Appsync things.
https://docs.aws.amazon.com/appsync/latest/devguide/resolver-mapping-template-reference-dynamodb.html

**Comment by erezrokah** [comment]
Just some stuff that came to mind when I was thinking about this:

1. Interface similar to `s3` integration.
2. For `PutItem`/`GetItem`/`DeleteItem` we need to figure out the key schema (configured by the user? Maybe we can figure it out dynamically).
3. How to handle composite keys? Maybe postpone support for them.
3. Need to write a generic version of this example to be used for mapping `GET` responses:

```
{
  "commentId": "$elem.commentId.S",
  "userName": "$elem.userName.S",
  "message": "$elem.message.S"
}
```

5. Support `GET` without a specific key to list all items?

**Comment by theburningmonk** [comment]
how about something like this to begin with:

```
dynamodb:
  path: /ddb/{hashKey}
  method: post
  action: PutItem
  table: { Ref: MyTable }
  hashKey:
    pathParam: hashKey
  rangeKey:   # optional
    queryStringParam: rangeKey  
```
and assume the Item to be coming from the POST body? e.g.
```
{
  "firstName": ...,
  "lastName": ...
}
```

Maybe we'd need to insert the hash and range key into the body the payload as well before we forward the request to DDB:
```
{
  "hashKey": ...,
  "rangeKey": ...,
  "firstName": ...,
  "lastName": ...
}
```

There's no need to deal with the body for `GetItem` and `DeleteItem`. There are other actions, which I'm not sure we should support - `UpdateItem`, `Query` and `Scan` since they have to deal with query expressions, expressions attributes and expression attribute values.

**Comment by erezrokah** [comment]
I was thinking of something similar:

```
# creates a new comment under the comments collection
dynamodb:
  path: /comments
  method: post # post is always mapped to PutItem
  table: { Ref: MyTable }
  # this is a bit ugly I know
  hashKey: '{ "S": "$util.autoId()" }' # context based hash key
  rangeKey:  '{ "S" : "$context.requestId" }' # optional, context based hash key

# creates or updates a comment
dynamodb:
  path: /users/{hashKey}
  method: put # put is always mapped to PutItem
  table: { Ref: MyTable }
  hashKey:
    pathParam: hashKey
  rangeKey:   # optional
    queryStringParam: rangeKey 

# updates an existing comment
dynamodb:
  path: /users/{hashKey}
  method: patch # patch is always mapped to UpdateItem
  table: { Ref: MyTable }
  hashKey:
    pathParam: hashKey
  rangeKey:   # optional
    queryStringParam: rangeKey

# deletes an existing comment
dynamodb:
  path: /users/{hashKey}
  method: delete # delete is always mapped to DeleteItem
  table: { Ref: MyTable }
  hashKey:
    pathParam: hashKey
  rangeKey:   # optional
    queryStringParam: rangeKey    
```

I think the action can be inferred from the method, but I might be wrong.
Using `path: /comments` is to allow "server" generated ids or for `$context.identity.cognitoIdentityId` (let's say you're populating a users table and don't trust the client).

As for `Query` and `Scan` there is also pagination to consider, so maybe it is better to wait for more use cases.

**Comment by theburningmonk** [comment]
My reservation about inferring the action with HTTP method (when I was working on the S3 proxy) was that I've seen a lot of "command" patterns - e.g. `POST /path/to/resource/delete` => `DELETE` - being used in the enterprise instead of proper HTTP verbs. Thinking about it again though, it might not be relevant nowadays, more of a thing in the past, haven't seen that in the wild in recent years.

That said, we didn't infer the action for the S3 service proxy, so whatever we decide to do here we should go back and change the S3 service proxy so we're internally consistent.

Or, maybe there's a compromise: make `action` an optional override, if you don't specify it then we'll infer from the HTTP action? Would be backward compatible for the S3 service proxy too.

**Comment by horike37** [comment]
I was thinking of similar with you guys. 
Additionally, It may need `condition` property with putitem action something like the following since there is a case which prevent overriding item by same Primary key with using `attribute_not_exists`

```
dynamodb:
  path: /ddb/{hashKey}
  method: post
  action: PutItem
  table: { Ref: MyTable }
  hashKey:
    pathParam: hashKey
  rangeKey:   # optional
    queryStringParam: rangeKey  
  condition: attribute_not_exists(hashKey)
```

And agreed with inferring from the HTTP action.

>Or, maybe there's a compromise: make action an optional override, if you don't specify it then we'll >infer from the HTTP action? Would be backward compatible for the S3 service proxy too.

I like this compromise. Would be better to support also for the improper HTTP action as @theburningmonk commented.
