### ISSUE TITLE
Custom Role for Api Gateway missing configuration

### ISSUE THREAD

**Issue by ClaudioCiociola** [horike37/serverless-apigateway-service-proxy#40]
When I configure in the serverless.yml the Api Gateway proxy for the s3 bucket, there is no way to define a custom Role for it. The plug-in will always create a role based on a random string, plus the base name of the project: `arn:aws:iam::541706693212:role/{basename+stage}-ApigatewayToS3Role-55508IP5RTGDQ`

Since I have a custom Role declared in the serverless configuration
```
XxxxS3Role:
      Type: 'AWS::IAM::Role'
      Properties:
        Path: /
        RoleName: 'xxxx-s3-role-${self:custom.currentStage}'
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - apigateway.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: 'xxxx-s3-policy-${self:custom.currentStage}'
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                - Effect: 'Allow'
                  Action:
                    - 's3:PutObject'
                    - 's3:DeleteObject'
                    - 's3:GetObject'
                  Resource:
                    Fn::Join:
                      - ''
                      - - 'arn:aws:s3:::'
                        - 'Ref': 'xxxxS3Bucket'
```

I tried to use this with the plugin in any way that I could imagine, but it gives me error in the template format, for example in this way:
```
apiGatewayServiceProxies:
    - s3:
        roles: Ref: XxxxS3Role
        path: /xxx-upload
        method: put
        action: PutObject
        bucket:
          Ref: SwarmS3Bucket
        key:
            queryStringParam: path
        cors: ${self:custom.corsPolicies}
```
