### ISSUE TITLE
[Feature request] Missing binary support for media files

### ISSUE THREAD

**Issue by ClaudioCiociola** [horike37/serverless-apigateway-service-proxy#43]
When you configure the Api Gateway proxy for an s3 bucket to upload an image (or also some kind of documents/pdfs) it doesn't upload them properly since on the Gateway needs to be enabled the binary support for that kind of media type that you want to use.

That feature is located in the Api Gateway "setting" section of your GW, in the sub-section "Binary Media Types":
![Schermata 2019-09-25 alle 11 05 32](https://user-images.githubusercontent.com/43550066/65586659-d264a880-df84-11e9-9a4f-413ab3399df4.png)

After some research and head scratching. I found an extra plug-in ([Apigw Binary plug-in](https://serverless.com/plugins/serverless-apigw-binary/)) that solved me this problem but it would be really useful to add the list of binary media types directly in the configuration of the proxy, for example in this way with the list of MIME types:

```
apiGatewayServiceProxies:
    - s3:
        binaryMediaTypes:
           - image/png
           - image/jpg
           - application/pdf
           - .....
        path: /xxx-upload
        method: put
        action: PutObject
        bucket:
          Ref: XxxxS3Bucket
        key:
            queryStringParam: path
        cors: ${self:custom.corsPolicies}
```

If this feature request it's doable will prevent a lot of user to import a second plug-in to just make this parameter change.
