### ISSUE TITLE
SQS Method Request HTTP Headers

### ISSUE THREAD

**Issue by Vlaaaaaaad** [horike37/serverless-apigateway-service-proxy#44]
Hi,

I am unsure if this is me failing or if this is unsupported. Apologies in advance if this is me failing.

I am trying to propagate some HTTP headers from the API Gateway request to the SQS queue in `MessageAttributes`. The idea is that I have a trace header that I want to go into the SQS `MessageAttributes`. Similar to AWS X-Ray.

I can say that I want that header sent to `MessageAttributes` in SQS by using `requestParameters`:
```yaml
apiGatewayServiceProxies:
  - sqs:
      path: /sqs
      method: post
      queueName: gatewaySqs
      cors:
        origin: '*'
        headers:
          - Content-Type
          - X-Amz-Date
          - Authorization
          - X-Api-Key
          - X-Amz-Security-Token
          - X-Amz-User-Agent
          - X-Honeycomb-Trace
        allowCredentials: false

      requestParameters:
        'integration.request.querystring.MessageAttributes.1.Name': "'x-honeycomb-trace'"
        'integration.request.querystring.MessageAttributes.1.Value.DataType': "'String'"
        'integration.request.querystring.MessageAttributes.1.Value.StringValue': "method.request.header.X-Honeycomb-Trace"
```

The issue is that anything in `method.request.header` has to be previously defined in _Method Request_, as per AWS:
> Mapping value: A URL path part, URL query string parameter or HTTP header defined in the Method Request. These follow the naming convention method.request.{"path" | "querystring" | "header" | "multivaluequerystring" | "multivalueheader"}.{param_name}. E.g. method.request.querystring.myparam. Choose one of path, querystring or header depending on whether you're mapping from a URL path, URL query string or HTTP header respectively. **param_name corresponds to the name explicitly given to the parameter in the Method Request set, i.e. the parameter needs to have been defined in the Method Request setup first**. Alternatively, wrap a value in single quotes for static values. E.g. 'my_static_value'.

I can confirm that setting an `X-Honeycomb-Trace` header in _Method Request_ -> _HTTP Request Headers_ and then applying the above works. 
Is there a way to specify that header with this plugin? Am I missing something?
