### ISSUE TITLE
converting apigateway queryparams  to sqs Message Body object

### ISSUE THREAD

**Issue by 2dev2** [horike37/serverless-apigateway-service-proxy#45]
hi,

I want to insert some predefined query params from apigateway to sqs as part of message body, How we can achieved that..

?text=this_is_test_message&id=3

in the sqs we should be able to store this data as an object {text:this_is_test_message, id:3}

Please give some idea how we can achieved this.

**Comment by erezrokah** [comment]
Hey @2dev2 I think once #46 is merged you should be able to do something like this:

```
custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /sqs
        method: get
        queueName: { 'Fn::GetAtt': ['SqsQueue', 'QueueName'] }
        cors: true
        acceptParameters:
          'method.request.querystring.body': true
        requestParameters:
          'integration.request.querystring.MessageBody': 'method.request.querystring.body'

resources:
  Resources:
    SqsQueue:
      Type: 'AWS::SQS::Queue'
```
Then send a `GET` request to `https://*******.execute-api.us-east-1.amazonaws.com/dev/sqs?body={ "text": "this_is_test_message", "id": 3 }`

Will that work for you?

**Comment by 2dev2** [comment]
Yup, this looks promising.
Thanks a lot, This kind of scenario will be fulfilled.

**Comment by 2dev2** [comment]
Thanks for looking into it and proposing the solution.
But in Our case  we don't have control over get API query structure, so it will not work for me.

In our case we are integrating with third party and they can't change their get query params structure
is there any way to accept multiple query-params and convert them to integration MessageBody, like aws apigateway does in integration part.

**Comment by erezrokah** [comment]
Currently the plugin doesn't support using request templates for SQS:
https://github.com/horike37/serverless-apigateway-service-proxy/blob/f36ef477116fb897aa4f21aa50a26eac1feac46c/lib/package/sqs/compileMethodsToSqs.js#L63

I'll have to look into it first to see if I can get SQS service proxy working with a request template instead request parameters.

Another (ugly) workaround might be to do the following:

```yaml
custom:
  apiGatewayServiceProxies:
    - sqs:
        path: /sqs
        method: get
        queueName: { 'Fn::GetAtt': ['SqsQueue', 'QueueName'] }
        cors: true
        acceptParameters:
          'method.request.querystring.text': true
          'method.request.querystring.id': true
        requestParameters:
          'integration.request.querystring.MessageBody': "''"
          'integration.request.querystring.MessageAttribute.1.Name': "'text'"
          'integration.request.querystring.MessageAttribute.1.Value.StringValue': 'method.request.querystring.text'
          'integration.request.querystring.MessageAttribute.1.Value.DataType': "'String'"
          'integration.request.querystring.MessageAttribute.2.Name': "'id'"
          'integration.request.querystring.MessageAttribute.2.Value.StringValue': 'method.request.querystring.id'
          'integration.request.querystring.MessageAttribute.2.Value.DataType': "'Number'"

resources:
  Resources:
    SqsQueue:
      Type: 'AWS::SQS::Queue'
```
