### ISSUE TITLE
[BUG] Authorization with COGNITO_USER_POOLS not works

### ISSUE THREAD

**Issue by andrewalf** [horike37/serverless-apigateway-service-proxy#51]
I want to use cognito's user pool for auth and as said in documentation i write in my config file:

```
authorizationType: COGNITO_USER_POOLS
authorizerId: 'valid arn to user pool'
```

But i get error: **child "s3" fails because [child "authorizationType" fails because ["authorizationType" must be one of [CUSTOM]]]**

If i swith authorizationType to CUSTOM, then a get another error, that says that COGNITO_USER_POOLS is acceptable.

**Invalid authorizer ID specified. Setting the authorization type to CUSTOM or COGNITO_USER_POOLS requires a valid authorizer**

**Comment by erezrokah** [comment]
Hey @andrewalf, thank you for opening this.
I'll try to have a look by the end of the week

**Comment by erezrokah** [comment]
To use a custom authorizer you should have something like this:

```yaml
service: authorization-custom

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - s3:
        path: /s3-custom-authorizer/{key}
        method: post
        action: PutObject
        bucket:
          Ref: S3Bucket
        key:
          pathParam: key
        cors: true
        authorizationType: CUSTOM
        authorizerId: { Ref: Authorizer }

functions:
  auth:
    handler: handler.auth
    cors: true

resources:
  Resources:
    S3Bucket:
      Type: 'AWS::S3::Bucket'

    Authorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        AuthorizerCredentials: { 'Fn::GetAtt': ['IamRoleLambdaExecution', 'Arn'] }
        IdentitySource: method.request.header.Authorization
        AuthorizerUri:
          Fn::Join:
            - ''
            - - 'arn:aws:apigateway:'
              - { Ref: 'AWS::Region' }
              - ':lambda:path/2015-03-31/functions/'
              - { 'Fn::GetAtt': ['AuthLambdaFunction', 'Arn'] }
              - /invocations
        Name: 'CustomAuthorizer'
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: TOKEN

  Outputs:
    S3BucketName:
      Value:
        Ref: S3Bucket

```

To use a cognito authorizer  something like this:

```yaml
service: authorization-cognito

provider:
  name: aws
  runtime: nodejs12.x

plugins:
  - serverless-apigateway-service-proxy

custom:
  apiGatewayServiceProxies:
    - s3:
        path: /s3-custom-authorizer/{key}
        method: post
        action: PutObject
        bucket:
          Ref: S3Bucket
        key:
          pathParam: key
        cors: true
        authorizationType: COGNITO_USER_POOLS
        authorizerId: { Ref: Authorizer }

resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket

    CognitoPool:
      Type: AWS::Cognito::UserPool

    Authorizer:
      Type: AWS::ApiGateway::Authorizer
      Properties:
        IdentitySource: method.request.header.Authorization
        ProviderARNs:
          - Fn::GetAtt: [CognitoPool, Arn]
        Name: 'CognitoAuthorizer'
        RestApiId:
          Ref: ApiGatewayRestApi
        Type: COGNITO_USER_POOLS

  Outputs:
    S3BucketName:
      Value:
        Ref: S3Bucket

```

The plugin doesn't let you set a `authorizerId` for `COGNITO_USER_POOLS` per AWS documentation:
https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/aws-resource-apigateway-method.html#cfn-apigateway-method-authorizationtype

![image](https://user-images.githubusercontent.com/26760571/69322032-ccb9d500-0c4c-11ea-9f43-f06eb6685399.png)

Which seems like a mistake in the docs, since that's the only way I got it to work...

I'll open a PR with a fix for `COGNITO_USER_POOLS` soon
