### ISSUE TITLE
manage 404 when proxy to an s3 bucket

### ISSUE THREAD

**Issue by fabien-h** [horike37/serverless-apigateway-service-proxy#63]
Hi and thanks for the package :)

Is there a way to manage the 404 in API gateway when proxying to an s3 bucket?

like so:
```
    - s3:
        path: /{myKey}
        method: get
        action: GetObject
        bucket:
          Ref: S3Bucket
        key:
          pathParam: myKey
        cors: true
```

=> this one means that if there is a file for `myKey`, it will be served. But if there is no file for the requested key, how could we redirect everything to a 404 file ?

**Comment by fabien-h** [comment]
By the way, I tried to make the bucket a website host like this:

```
resources:
  Resources:
    S3Bucket:
      Type: AWS::S3::Bucket
      Properties:
        AccelerateConfiguration:
          AccelerationStatus: Enabled
        BucketName: __my-bucket-name__
        WebsiteConfiguration:
          ErrorDocument: index.html
          IndexDocument: index.html
```

It's working when I visit the s3 website endpoint. But not when I visit the API Gateway endpoint.

**Comment by theburningmonk** [comment]
@fabien-h if you have turned on website hosting on S3 why would you still need the API Gateway service proxy?

**Comment by fabien-h** [comment]
This would work only if I were to use `api.ndd.tld` for the api and `ndd.tld` for the website. But I would prefer having `ndd.tld/api` for the api.

(and I will have multiple domain names pointing on the same bucket, it would be annoying to have one bucket per domain)

```
    - s3:
        path: /
        method: get
        action: GetObject
        pathOverride: 'index.html'
        bucket:
          Ref: S3Bucket
        key:
          pathParam: myKey
        cors: true
```

Allow me to redirect `/` to `/index.html`. But not `/anything`.
