### ISSUE TITLE
add support for S3

### ISSUE THREAD

**Issue by theburningmonk** [horike37/serverless-apigateway-service-proxy#9]
maybe something along the lines of

```yml
custom:
  apiGatewayServiceProxies:
    - s3:
        path: /
        method: post
        action: GetObject # maps to s3:GetObject action
        bucket: "hard-coded bucket name"
        key: "hard-coded object key"
        cors: true
    - s3:
        path: /{filename}
        method: post
        action: PutObject # maps to s3:PutObject action
        bucket: "hard-coded bucket name"
        # let caller specify the key via path parameter
        key.$: filename
        cors: true
```
